# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailReaderUiv2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(628, 524)
        self.readfileButton_1 = QtWidgets.QPushButton(Form)
        self.readfileButton_1.setGeometry(QtCore.QRect(260, 30, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readfileButton_1.sizePolicy().hasHeightForWidth())
        self.readfileButton_1.setSizePolicy(sizePolicy)
        self.readfileButton_1.setMaximumSize(QtCore.QSize(16777212, 16777215))
        self.readfileButton_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.readfileButton_1.setBaseSize(QtCore.QSize(0, 0))
        self.readfileButton_1.setObjectName("readfileButton_1")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 85, 16))
        self.label.setStyleSheet("font: 8pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(110, 30, 142, 21))
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(320, 30, 84, 21))
        self.label_2.setStyleSheet("font: 8pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(400, 30, 142, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.readfileButton_2 = QtWidgets.QPushButton(Form)
        self.readfileButton_2.setGeometry(QtCore.QRect(550, 30, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readfileButton_2.sizePolicy().hasHeightForWidth())
        self.readfileButton_2.setSizePolicy(sizePolicy)
        self.readfileButton_2.setMaximumSize(QtCore.QSize(16777212, 16777215))
        self.readfileButton_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.readfileButton_2.setBaseSize(QtCore.QSize(0, 0))
        self.readfileButton_2.setObjectName("readfileButton_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(250, 80, 72, 15))
        self.label_3.setStyleSheet("font: 8pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 80, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.readfileButton_3 = QtWidgets.QPushButton(Form)
        self.readfileButton_3.setGeometry(QtCore.QRect(430, 80, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readfileButton_3.sizePolicy().hasHeightForWidth())
        self.readfileButton_3.setSizePolicy(sizePolicy)
        self.readfileButton_3.setMaximumSize(QtCore.QSize(16777212, 16777215))
        self.readfileButton_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.readfileButton_3.setBaseSize(QtCore.QSize(0, 0))
        self.readfileButton_3.setObjectName("readfileButton_3")
        self.startTrainButton = QtWidgets.QPushButton(Form)
        self.startTrainButton.setGeometry(QtCore.QRect(500, 80, 93, 28))
        self.startTrainButton.setObjectName("startTrainButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_4.setStyleSheet("font: 8pt \"微软雅黑\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 130, 142, 21))
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.readfileButton_4 = QtWidgets.QPushButton(Form)
        self.readfileButton_4.setGeometry(QtCore.QRect(260, 130, 41, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readfileButton_4.sizePolicy().hasHeightForWidth())
        self.readfileButton_4.setSizePolicy(sizePolicy)
        self.readfileButton_4.setMaximumSize(QtCore.QSize(16777212, 16777215))
        self.readfileButton_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.readfileButton_4.setBaseSize(QtCore.QSize(0, 0))
        self.readfileButton_4.setObjectName("readfileButton_4")
        self.startTestButton = QtWidgets.QPushButton(Form)
        self.startTestButton.setGeometry(QtCore.QRect(320, 130, 93, 28))
        self.startTestButton.setObjectName("startTestButton")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(130, 80, 75, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 101, 16))
        self.label_5.setStyleSheet("font: 8pt \"微软雅黑\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 611, 361))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.readfileButton_1.setText(_translate("Form", "..."))
        self.label.setText(_translate("Form", "spam训练集:"))
        self.label_2.setText(_translate("Form", "ham训练集："))
        self.readfileButton_2.setText(_translate("Form", "..."))
        self.label_3.setText(_translate("Form", "分词集："))
        self.readfileButton_3.setText(_translate("Form", "..."))
        self.startTrainButton.setText(_translate("Form", "开始训练"))
        self.label_4.setText(_translate("Form", "测试邮件集："))
        self.readfileButton_4.setText(_translate("Form", "..."))
        self.startTestButton.setText(_translate("Form", "开始测试"))
        self.comboBox.setItemText(0, _translate("Form", "贝叶斯"))
        self.comboBox.setItemText(1, _translate("Form", "KNN"))
        self.label_5.setText(_translate("Form", "训练算法选择："))

